name: image_pdf_upload
description: A new Flutter project.


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'







dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6+3
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.0





flutter:




  uses-material-design: true































